### PR TITLE
Always elevate by 1000 in `zIndex` when node is selected

### PR DESCRIPTION
**Pull request by neo**
Instead of only elevating when `zIndex` is unset

### CODE REVIEW

**Comment by moklick** [comment]
yep, I agree. Thanks @neo!

**Comment by moklick** [comment]
will be released with #2559

**Comment by neo** [comment]
> will be released with #2559

I'm wondering, when #2559 is merged including the same commit, and if we keep this PR open, it would automatically mark this as "merged" rather than "closed" currently? Not 100% sure, just a consideration to better differentiate which PRs are actually merged.

I also noticed there was #2560, which I think we could've changed the "base" of this PR to `next-release` and achieve the same? just suggesting what might be more clear and efficient 😆 

And thank you again for this library! 🎉

**Comment by moklick** [comment]
@neo yep! The problem here was that I created a new branch based on your work (I needed to add a changeset) and then merged it before I changed the base branch of this PR. Afterwards it's not possible anymore unfortunately..

**Comment by neo** [comment]
hey Moritz! sorry not being clear enough 😅 I meant next time for future considerations; I knew this was settled and couldn't be changed.

**Pull request closed without merging**
