### PR TITLE
Feat/dragedge

### PR DESCRIPTION
**Pull request by moklick**

### CODE REVIEW

**Comment by moklick** [comment]
Hey @zcmgyu 

can you have another look at it before we merge it?

**Comment by zcmgyu** [comment]
I will review it on the next working day.

**Comment by moklick** [comment]
We are only displaying the move cursor when you pass the `onUpdateEdge` function.

**Comment by zcmgyu** [comment]
@moklick I confused when having multiple edges starting from one source. I think we should bring the selected edge to the front for easy dragging. I've tried setting z-index into the selected edge but it still doesn't work.

Screen Shot 2020-11-30 at 14 57 07

**Comment by moklick** [comment]
Unfortunately there is no z-index for SVGs. We could order the edges in a way that the selected ones are on top. Do you see any problems besides that?

**Comment by zcmgyu** [comment]
@moklick Besides that, I think everything is OK.

**Comment by moklick** [comment]
Ok, I will keep that in mind but I think we can already merge this feature. I added a hover effect, that helps to recognize which edge updater is hovered.

**Comment by zcmgyu** [comment]
@moklick Thanks <3

**Comment by moklick** [comment]
Thank you for your work here @zcmgyu

**Comment by moklick** [comment]
Released in v8.1.0. Example: https://reactflow.dev/examples/updatable-edge/

**Pull request merged**
