### PR TITLE
Feature: Draggable edge

### PR DESCRIPTION
**Pull request by zcmgyu**
**Feature request:** https://github.com/wbkd/react-flow/issues/549
**Description:**
This feature allows users to press at either end of the edge and drag to the target node to update the connection of edge.
The developer could use `onEdgeUpdate` to handle this event.

I've made an example: 
https://github.com/zcmgyu/react-flow/blob/bd63a0131ace6a626f0e88ba3e62ac677cd990ca/example/src/DraggableEdge/index.js

Draggle-Edge

### CODE REVIEW

**Comment by moklick** [comment]
Hey @zcmgyu 

thanks for your work here! I am waiting for the feedback from #543.

**Comment by moklick** [comment]
I started to work on this PR on the `feat/dragedge` branch.

**Comment by diegohmac** [comment]
When is it going to master?

**Comment by zcmgyu** [comment]
I've reviewed your work in `feat/dragedge`. Need to pass onEdgeUpdate to EdgeComponent to it work as expected.
Hope you merge it asap.

```
// react-flow/src/container/EdgeRenderer/index.tsx

<EdgeComponent
      ...
      onEdgeUpdate={props.onEdgeUpdate}
    />
```

**Comment by zcmgyu** [comment]
@moklick One more thing, after dragging the edge to the new position, all old props of the old edge were not passed to the new edge at all


```
// wrapEdge.tsx
        const onConnect = (connection: Connection) => {
          if (onEdgeUpdate) {
            const edgeElement: Edge = {
              ...props,
              id,
              source,
              target,
              sourceHandle: sourceHandleId,
              targetHandle: targetHandleId,
              type,
            };

            onEdgeUpdate(edgeElement, connection);
          }
        };
```

**Comment by moklick** [comment]
Hey @zcmgyu 

we will continue here #726

**Pull request closed without merging**
