### PR TITLE
feat(fitView): added option to exclude hidden nodes

### PR DESCRIPTION
**Pull request by ambroseus**
implementation for #875

### CODE REVIEW

**Comment by ambroseus** [comment]
fit view examples with hidden nodes:
Selection_011
Selection_012

**Comment by ambroseus** [comment]
added fitViewParams prop to Control component 
```jsx
const FlowWithControls = () => (
  <ReactFlow elements={elements}>
    <Controls fitViewParams={ excludeHidden: true } />
  </ReactFlow>
);
```

**Comment by ambroseus** [comment]
@moklick  or maybe no need to add `excludeHidden` option.. just force to exclude.. what do you think? ;)

**Comment by moklick** [comment]
Hey @ambroseus 

thanks for your support :) I really like the idea. What do you think about renaming it to `includeHidden` which is set to `false` by default?

**Comment by ambroseus** [comment]
> renaming it to `includeHiddenNodes` which is set to `false` by default?
awesome! :)

**Comment by ambroseus** [comment]
@moklick  done, please review

**Comment by moklick** [comment]
Looks good! Thanks :)

**Comment by moklick** [comment]
Released in v8.8.0

**Pull request merged**
