### PR TITLE
fix(connectionLine): sourceHandle with connectionMode = loose

### PR DESCRIPTION
**Pull request by clementloridan**
Fix `TypeError: Cannot read property 'find' of null` if the connectionMode is "loose" and all the handles are "source".
-> Crash from ConnectionLine because in `handleBounds` of a sourceNode: `target` or `source` can be null.

### CODE REVIEW

**Comment by moklick** [comment]
Hey @clementloridan. Thanks for the PR :) Could you remove the example adjustments and the react downgrade? Then I will merge it.

**Comment by moklick** [comment]
@li4man0v This is strange I don't get an error when do that.

**Comment by li4man0v** [comment]
https://user-images.githubusercontent.com/5625684/139734176-599ba30c-1831-424b-a5be-b47e8075acd2.mov

This is what I see after fresh repo setup.

**Comment by IOR88** [comment]
@moklick when thix fix will be merged ? we have the same problem in our app, really looking forward to thix fix :)

**Pull request merged**
