### PR TITLE
Allow specifying multiple keys for selection and deletion

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/wbkd/react-flow/issues/1269
Fixes https://github.com/wbkd/react-flow/issues/1268
Fixes https://github.com/wbkd/react-flow/issues/1054
Fixes https://github.com/wbkd/react-flow/issues/1002

### CODE REVIEW

**Comment by saswatds** [comment]
Hi, I wanted to understand the prospects of this PR getting merged? Without this, the UX in windows and Linux environment is abysmal.

**Comment by moklick** [comment]
I already worked on this feature on the `refactor/keys` branch.. Maybe it would be better to use a library for this. I would like to support key combinations like `Meta+s` and multiple possibilities like `['Del', 'Backspace']`.

In my branch I changed the API to support combinations by passing an array. I think your approach to use an array for multiple possibilities is more common so I would go for this API instead. I will see If I can find a good tiny library that fits our needs here.

**Comment by Ark-kun** [comment]
> I didn't merged it because it's a breaking change

Perhaps we can keep supporting the old parameter names as well.

**Comment by Ark-kun** [comment]
We've released our project and our Mac users are really confused and cannot delete the nodes =(

**Comment by moklick** [comment]
This feature will be available in the next major release. You can check the API changes and installation instructions for the bete in this PR #1555.

**Pull request closed without merging**
