### PR TITLE
feat(deleteElements): add `deleteElements` method

### PR DESCRIPTION
**Pull request by pengfu**
hi @moklick ,
As mentioned in [https://github.com/wbkd/react-flow/pull/2432](https://github.com/wbkd/react-flow/pull/2432), I have just redo the PR againest v11 branch.
Reactflow is an excellent library, and I really appreciate your excellent job!!

### CODE REVIEW

**Comment by moklick** [comment]
now it's `main` (we already merged v11).. 

Could you run it locally now? I remember that you had some issues with the new repo structure.

**Comment by pengfu** [comment]
Yes, I think your idea is better. 
Then what about the the method typed like `deleteElements(nodeIds, edgeIds): (string[], string[])=>void` , `nodeIds` and `edgeIds`  may represent the nodes or edges that user initially want to remove ? 
I'll try to do this change right away

**Comment by moklick** [comment]
I would suggest an API like this one:

```js
type DeleteElementsOptions = {
  nodes?: (Partial<Node> & { id: Node['id'] })[],
  edges?: (Partial<Edge> & { id: Edge['id'] })[]
};

const deleteElements = ({ nodes, edges }: DeleteElementsOptions) => void
```

So instead of two separated params I would pass an object with optional node and edge arrays that could also just be id arrays.

**Comment by pengfu** [comment]
hey @moklick , your suggesiton seems better ,  I have just tried to do the change and gave an example in usereactflow part.

**Comment by pengfu** [comment]
Besides, I have found out a strange behavior that occurs before my commits yet I am not sure if it is an issue.
In useReactFlow example, as described on [https://www.techiediaries.com/react-18-useeffect/](https://www.techiediaries.com/react-18-useeffect/), useEffect may called twice in development strict mode, 
this lead to `addEdges` called twice
`useEffect(() => {
    addEdges({ id: 'e3-4', source: '3', target: '4' });
  }, [addEdges]);`
when we tried to delete Node 3 ,  finnaly what shows on canvas is:

image

**Comment by moklick** [comment]
closed in favour of #2536

**Pull request closed without merging**
