### PR TITLE
Updated d3-zoom instance to include touchable to fix mobile interaction

### PR DESCRIPTION
**Pull request by balbatross**
Fixes the issue of mobile browsers not being able to interact with the background (at least on chrome dev tools)

### CODE REVIEW

**Comment by moklick** [comment]
Hey @balbatross 

we would like to keep the d3-zoom default. Your change would always register the touch event listeners. We could think about passing this as an option.

**Comment by meatflavourdev** [comment]
> Hey @balbatross
> 
> we would like to keep the d3-zoom default. Your change would always register the touch event listeners. We could think about passing this as an option.

Is that to say that mobile is unsupported by default? Just curious.. haven't done much testing on mobile.

**Comment by balbatross** [comment]
@meatflavourdev there's a few missing functions for mobile, I'll have some free time to make a better PR sometime in the next week

**Comment by moklick** [comment]
No this only affects the dev tools mobile view. Real touch screens get recognized.

**Comment by moklick** [comment]
I you make this an option I would merge it but it's not a good default. Reopen if you are still interested in this feature.

**Pull request closed without merging**
