### PR TITLE
add twin lines background variant

### PR DESCRIPTION
**Pull request by Elringus**
This adds new background variant type `TwinLines` (4th on the screenshot below).

scrn

First line is controlled by the same properties as used in `Lines` variant; second line width, gap and color are controlled with `twinLineWidth`, `twinGap` and `twinColor` properties.

Related discussion: https://github.com/wbkd/react-flow/discussions/2937

### CODE REVIEW

**Comment by moklick** [comment]
Hey @Elringus 

thanks for your help here! It's a good idea to reuse the lines background variant 👍 

I would like to suggest some changes:

- rename variant to "grid" or "gridLines"
- rename `twinGap` to `gridFactor` (5 would be gap * 5, and so on)
- remove `twinColor` and just use `color`
- remove `twinLineWidth` and always use 2*lineWidth or whatever looks reasonable

what do you think about this?

**Comment by Elringus** [comment]
- I thought about "grid", but "lines" are also basically a grid in the end, which could be confusing. The key here is adding one more grid pattern with a different color, width and gap. Imho, optimal solution here would be replacing pattern enum with standalone background components for each pattern type, so that they could have their own props, but that's a breaking change.
 - Fine be me, I've also thought about it, but figured someone may want to use different x,y gaps for the second pattern, given the option is already available for the main pattern.
 - An option to set different color for the second pattern is critical for my use case; changing width won't look as clean.
 - Again, fine be me, as I don't change the width for the second pattern, only color; but may be desired in some other cases.

**Comment by Elringus** [comment]
I've made an alternative solution via #2941, which is probably better that this one.

**Comment by moklick** [comment]
good points. I would also prefer an API like this:

```jsx
<Background>
  <BackgroundPattern />
</Background>
```

maybe that's something for v12. 

closed in favour of #2941

**Pull request closed without merging**
