### PR TITLE
Support react-flow inside shadow root

### PR DESCRIPTION
**Pull request by TheUnderScorer**
Hi!

Currently I am working on React project that is contained inside shadow root, and I've noticed that connection handlers were not working correctly, mostly due to `document.elementFromPoint` used in src/components/Handle/handler.ts because they couldn't detect elements stored inside shadow root. I've added new prop "document" that gives us ability to pass either document or shadow root that will be later used in connection handle. 

Let me know what you think! I know that it's kinda edge case, but it might be useful for other ppl as well 😄

### CODE REVIEW

**Comment by moklick** [comment]
This is interesting. What is the use case for putting it inside shadow root?

**Comment by TheUnderScorer** [comment]
In my case it's a chrome extension, thanks to putting the whole content script inside shadow root I make sure that all styles and scripts are encapsulated.

**Comment by moklick** [comment]
Thanks for your work here. I think this would crash in a nextjs context for example because there is window is undefined there. Could you add some checks when using window?

**Comment by TheUnderScorer** [comment]
Done!

**Comment by moklick** [comment]
Looks good. One more thing: What about the key handlers? Right now they are added to the window. Is this an issue for you?

**Comment by TheUnderScorer** [comment]
They've been working fine for me, so I guess that's it from my side! :)

**Pull request merged**
