### PR TITLE
feat(core): add option to enable/disable replacing id when updating an edge

### PR DESCRIPTION
**Pull request by bcakmakoglu**

### CODE REVIEW

**Comment by moklick** [comment]
thanks man! Can you put shouldReplaceId in an object. That way we are more flexible with adding even more options later on :)

**Comment by bcakmakoglu** [comment]
Sure 👍

**Comment by bcakmakoglu** [comment]
@moklick PR is updated btw =)

**Comment by moklick** [comment]
Thanks @bcakmakoglu 🙌

**Pull request merged**
