### PR TITLE
Feat/lock

### PR DESCRIPTION
**Pull request by raichuk**
This PR contains a very small feature to allow users to lock the interaction, and eventually, unlock it with the nodes and edges.
It's used through a button on Controls plugin.

Notes:
- The svg used where just for testing purposes and could be improved.
- Following the README directions to start development lacks a step, that is installing the deps for the examples.
- I've tried my best to follow the pattern for commit messages and branch names.

It's my first time contributing here, so please any changes to this PR will be applied immediatly.

### CODE REVIEW

**Comment by moklick** [comment]
This looks really good! Thanks for your work. Could you open the unlocked lock a little wider?

**Comment by raichuk** [comment]
Thanks for the feedback!

I will move the button to the last vertical position and try my best to update this SVG.

Will keep you updated.

**Comment by raichuk** [comment]
Icon is updated, svg manipulation is not my best skill.

**Comment by moklick** [comment]
Thanks again for your help :) It's merged now. We will do a new release in the next days

**Comment by raichuk** [comment]
Amazing process!.

I am actively using the library so, I am actually writing a `dev.to` article about it.
So if you need anything else I will be happy to help!

Thanks and keep this excellent work.

**Comment by moklick** [comment]
Nice! Let us know when you publish the article :)

**Comment by raichuk** [comment]
Will do

**Comment by D-Niermann** [comment]
Hello, I have a question: How can I access this function (the lock) via code? I want to automatically trigger the lock button when another event happens.

Thank you!

**Pull request merged**
