### PR TITLE
feat: add scrollToPan Handler

### PR DESCRIPTION
**Pull request by EmielW**
- add event handler to pan canvas when scrolling

### CODE REVIEW

**Comment by EmielW** [comment]
Hey @moklick 

I made a start on the `useScrollToPan` handler. What do you think of the solution so far? I'm not sure if the `GraphView` is the right location for the `scrollToPanHandler`. Let me know what you think and if there are any improvements I can make.

**Comment by moklick** [comment]
Thanks! I would not offer the possibility to adjust the scroll speed but I think we must consider the current zoom level. Maybe this could help https://stackoverflow.com/questions/55778403/d3-zoom-pan-axis-on-scroll-pan-axis-on-drag-zoom-axis-on-pinch

**Comment by EmielW** [comment]
Oke, I will take a look at that solution

**Comment by moklick** [comment]
In the meantime we introduced a `translateExtent` option which gives you the possibility to set the size of the pane. The new scrolling behaviour also needs to pay attention to that. Thanks for your efforts :)

**Comment by moklick** [comment]
I renamed the `master` branch to `main`. You need to open a new PR.

**Pull request closed without merging**
