### PR TITLE
Ensure node.position and node.__rf.position are in sync when node position is updated via drag and node.position property updates.

### PR DESCRIPTION
**Pull request by datoslabs**
Fix for issues #1425 and #1444.

### CODE REVIEW

**Review by rafaell-lycan — APPROVED** [review]

**Comment by moklick** [comment]
Hey @datoslabs.

With your changes the states are still out of sync. The ReactFlow user state position would not match with the internal one. If you would update another node data attribute the node would jump back to the old position. This can be seen in the update-node example.

**Comment by datoslabs** [comment]
@moklick, Could you please provide steps to reproduce it and I will resubmit the PR?  I have been using this fix in my dev environment without problems, maybe there's a scenario that I missed.

**Comment by moklick** [comment]
Sure! Go to http://localhost:3000/update-node , drag the upper node, change the label (with the input on the upper right) - The node will jump back to its old position.

**Comment by datoslabs** [comment]
Thank you @moklick, after more digging, I think I finally got it; the root cause is the use of shallow copy in `SET_ELEMENTS` reducer causing both `storeNode.position` and `propElement.position` to reference the same object instance when the user (I) also used shallow copy to update the position.  Based on this, I have made changes on my end to perform a deep clone to avoid further problems, I am not sure if you want to also make changes to the library.  On one hand, according to react best practices, HOC should ensure data objects are immutable, on the other hand, it appears that the logic in `SET_ELEMENTS` reducer intends to track element position between updates to selectively update __rf.position values which suggests the library should take steps to ensure it's not referencing the position object provided by the user.  Let me know what you think, I can make the simple fix in the reducer and resubmit the PR or you can update the documentation to clarify this behavior.

A more detailed explanation, for documentation purposes, is as follows:

The reason react-flow keeps 2 internal states of the node positions (ie `storeNode.position` vs `storeNode.__rf.position`) is to keep track of the on-screen position as well as user specified position via `setElements`.  This way if user altered the node position via node drag it can detect in the next 'setElements' update if the node position is updated programmatically by checking `if (storeNode.position.x !== propElement.position.x || storeNode.position.y !== propElement.position.y)` in the `SET_ELEMENTS` reducer thus avoiding the node jumping back to its old position after non-position updates such as label update in your scenario.  

This logic is sound except because position is a nested object and since the reducer uses a shallow copy, the position object inside the store (both `storeNode.position` as well as `storeNode.__rf.position`) is actually the same instance as the position object provided to `setElements` (ie `propElement`) after the 2nd time `SET_ELEMENTS` reducer is executed.  Because I included logic to auto layout the elements using dagre.js, when my graph is finally initialized, it would have called `SET_ELEMENTS` reducer twice.  Therefore, **before any node drag**, `propElement.position === storeNode.position === storeNode.__rf.position`; **after node drag**, `UPDATE_NODE_POS_DIFF` reducer is called and assigned a new instance to `storeNode.__rf.position` at which point `propElement.position === storeNode.position !== storeNode.__rf.position`.  Because This gives the illusion that node position is being updated by `setElements` before node drag even though `if (storeNode.position.x !== propElement.position.x || storeNode.position.y !== propElement.position.y)` always evaluates to false after being initialized.

**Comment by moklick** [comment]
I will close this because this is fixed in v10. Thanks for your input and your effort here @datoslabs 🙌

**Pull request closed without merging**
