### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by michaeltheobald**
added height, so the example shows something :)

### CODE REVIEW

**Comment by moklick** [comment]
Which browser are you using? The examples should be visible without setting a height (they already have 100% height).

**Comment by michaeltheobald** [comment]
> Which browser are you using? The examples should be visible without setting a height (they already have 100% height).

Hello Moritz,

Thanks for the quick answer. I am using Chrome at Version 86.0.4240.75. 
I could send you my sample project if you want.

BTW you're doing a great job with this framework in matter of documentation and examples!

Greetings,

Michael

**Comment by moklick** [comment]
The examples inside the "example" folder are meant for testing. They should work when you run `npm run dev`. 

Did you have problems because you copy pasted it and your parent container has no height?

**Comment by michaeltheobald** [comment]
Yes, I copy pasted. Sry to have bothered you.

**Comment by moklick** [comment]
no worries!

**Pull request closed without merging**
